# -*- coding: utf-8 -*-
"""K-means Regresi Linear.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ddxspnTLnGbmCTNTCH1hiB-eRpr3C5D6
"""

import sklearn.linear_model as lm
import pandas as pd
data=pd.read_csv("pizza.csv")
print(data)

var_index=['x1','x2']
x=data[var_index]
print(x)

y=data['y']
print(y)

lr=lm.LinearRegression()
lr.fit(x,y)
print("coef:",lr.coef_)

print("intercept",lr.intercept_)

print("persamaan regresi yg didapat:")
print("y = {0:.2f} + {0:.2f} {0:.2f}".format(lr.intercept_,lr.coef_[0],lr.coef_[1]))
print("y = {} + {} {}".format(lr.intercept_,lr.coef_[0],lr.coef_[1]))

import pandas as pd
import numpy as np

data=pd.read_csv("pizza.csv")
print(data)

data2=data.to_numpy()

print(data2)

X=data2[:,0:3]

print(X)

Y=data2[:,3]

print(Y)

Xt=X.transpose()

print(Xt)

XtX=Xt.dot(X)

print(XtX)

XtI=np.linalg.inv(XtX)

print(XtI)

XtY=Xt.dot(Y)

print(XtY)

b=XtI.dot(XtY)

print(b)

print("y = {} + {} {}".format(b[0],b[1],b[2]))